name: invoice-ninja
services:
  invoice-ninja:
    image: invoiceninja/invoiceninja:5.13.31@sha256:c0526fc0242f4bd145d0d225bb40e174841f67597a57215723f20f2c00c0698f
    container_name: invoice-ninja
    restart: unless-stopped
    user: "1500:1500"
    environment:
      - IN_USER_EMAIL=admin@roqueribeiro.com
      - IN_PASSWORD=ad178c4b-302f-44e6-937f-8c7808f23795
      - APP_URL=http://invoice-ninja-web
      - APP_KEY=base64:4doW1cidLuSqm7Z/BhPu/bn5HGnCKyEcSSlbVPTYYRU=
      - APP_CIPHER=AES-256-CBC
      - DB_HOST=invoice-ninja-db
      - DB_PORT=3306
      - DB_DATABASE=ninja
      - DB_USERNAME=ninja
      - DB_PASSWORD=ninja
      - REQUIRE_HTTPS=false
      - QUEUE_CONNECTION=database
      - IS_DOCKER=TRUE
    volumes:
      - /DATA/AppData/$AppID/data/public:/var/www/app/public
      - /DATA/AppData/$AppID/data/storage:/var/www/app/storage
      - /DATA/AppData/$AppID/data/php/php.ini:/usr/local/etc/php/php.ini
      - /DATA/AppData/$AppID/data/php/php-cli.ini:/usr/local/etc/php/php-cli.ini
    depends_on:
      - invoice-ninja-db
    networks:
      - invoice-ninja-network
    x-casaos:
      envs:
        - container: IN_USER_EMAIL
          description:
            en_US: "Container Variable: IN_USER_EMAIL"
            en_us: "Container Variable: IN_USER_EMAIL"
        - container: IN_PASSWORD
          description:
            en_US: "Container Variable: IN_PASSWORD"
            en_us: "Container Variable: IN_PASSWORD"
        - container: APP_URL
          description:
            en_US: "Container Variable: APP_URL"
            en_us: "Container Variable: APP_URL"
        - container: APP_KEY
          description:
            en_US: "Container Variable: APP_KEY"
            en_us: "Container Variable: APP_KEY"
        - container: APP_CIPHER
          description:
            en_US: "Container Variable: APP_CIPHER"
            en_us: "Container Variable: APP_CIPHER"
        - container: DB_HOST
          description:
            en_US: "Container Variable: DB_HOST"
            en_us: "Container Variable: DB_HOST"
        - container: DB_PORT
          description:
            en_US: "Container Variable: DB_PORT"
            en_us: "Container Variable: DB_PORT"
        - container: DB_DATABASE
          description:
            en_US: "Container Variable: DB_DATABASE"
            en_us: "Container Variable: DB_DATABASE"
        - container: DB_USERNAME
          description:
            en_US: "Container Variable: DB_USERNAME"
            en_us: "Container Variable: DB_USERNAME"
        - container: DB_PASSWORD
          description:
            en_US: "Container Variable: DB_PASSWORD"
            en_us: "Container Variable: DB_PASSWORD"
        - container: REQUIRE_HTTPS
          description:
            en_US: "Container Variable: REQUIRE_HTTPS"
            en_us: "Container Variable: REQUIRE_HTTPS"
        - container: QUEUE_CONNECTION
          description:
            en_US: "Container Variable: QUEUE_CONNECTION"
            en_us: "Container Variable: QUEUE_CONNECTION"
        - container: IS_DOCKER
          description:
            en_US: "Container Variable: IS_DOCKER"
            en_us: "Container Variable: IS_DOCKER"
      volumes:
        - container: /var/www/app/public
          description:
            en_US: "Container Path: /var/www/app/public"
            en_us: "Container Path: /var/www/app/public"
        - container: /var/www/app/storage
          description:
            en_US: "Container Path: /var/www/app/storage"
            en_us: "Container Path: /var/www/app/storage"
        - container: /usr/local/etc/php/php.ini
          description:
            en_US: "Container Path: /usr/local/etc/php/php.ini"
            en_us: "Container Path: /usr/local/etc/php/php.ini"
        - container: /usr/local/etc/php/php-cli.ini
          description:
            en_US: "Container Path: /usr/local/etc/php/php-cli.ini"
            en_us: "Container Path: /usr/local/etc/php/php-cli.ini"
  invoice-ninja-web:
    container_name: invoice-ninja-web
    image: nginx:1.29@sha256:1881968aff6f7cdcc4b888c00a11f4ce241ad7ec957e0cb4a9e19e93a3ff87ea
    restart: unless-stopped
    volumes:
      - /DATA/AppData/$AppID/data/nginx/invoice-ninja.conf:/etc/nginx/conf.d/default.conf
      - /DATA/AppData/$AppID/data/public:/var/www/app/public
    ports:
      - "8080:80"
    networks:
      - invoice-ninja-network
    x-casaos:
      volumes:
        - container: /etc/nginx/conf.d/default.conf
          description:
            en_US: "Container Path: /etc/nginx/conf.d/default.conf"
            en_us: "Container Path: /etc/nginx/conf.d/default.conf"
        - container: /var/www/app/public
          description:
            en_US: "Container Path: /var/www/app/public"
            en_us: "Container Path: /var/www/app/public"
      ports:
        - container: "80"
          description:
            en_US: "Container Port: 80"
            en_us: "Container Port: 80"
  invoice-ninja-db:
    image: mariadb:10.4@sha256:22edfe1c78349f8cae88bbb5c2873b7e6c515be767c91c691308ce57445806f3
    container_name: invoice-ninja-db
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=ad178c4b-302f-44e6-937f-8c7808f23795
      - MARIADB_USER=ninja
      - MARIADB_PASSWORD=ninja
      - MARIADB_DATABASE=ninja
    volumes:
      - /DATA/AppData/$AppID/data/mysql:/var/lib/mysql
    networks:
      - invoice-ninja-network
    depends_on:
      - invoice-ninja-init
    command:
      - mysqld
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--wait_timeout=28800"
      - "--log-warnings=0"
    x-casaos:
      envs:
        - container: MARIADB_ROOT_PASSWORD
          description:
            en_US: "Container Variable: MARIADB_ROOT_PASSWORD"
            en_us: "Container Variable: MARIADB_ROOT_PASSWORD"
        - container: MARIADB_USER
          description:
            en_US: "Container Variable: MARIADB_USER"
            en_us: "Container Variable: MARIADB_USER"
        - container: MARIADB_PASSWORD
          description:
            en_US: "Container Variable: MARIADB_PASSWORD"
            en_us: "Container Variable: MARIADB_PASSWORD"
        - container: MARIADB_DATABASE
          description:
            en_US: "Container Variable: MARIADB_DATABASE"
            en_us: "Container Variable: MARIADB_DATABASE"
      volumes:
        - container: /var/lib/mysql
          description:
            en_US: "Container Path: /var/lib/mysql"
            en_us: "Container Path: /var/lib/mysql"
  invoice-ninja-init:
    image: bash:5.3.15@sha256:a19c811ee9e97fa8a080001d82b8e0ded303f0795cffdb1cbd162731bc8ce208
    container_name: invoice-ninja-init
    volumes:
      - /DATA/AppData/$AppID/data:/tmp/data
    command:
      - /bin/sh
      - "-c"
      - "if [ ! -f /tmp/data/.init_complete ]; then echo 'Starting initialization process...' && if [ -f /tmp/data/init/init.sh ]; then echo 'Found init.sh, making it executable...' && chmod +x /tmp/data/init/init.sh && echo 'Executing init.sh...' && /tmp/data/init/init.sh && echo 'init.sh execution completed.' && touch /tmp/data/.init_complete && echo 'Initialization process finished.'; else echo 'Error: /tmp/data/init/init.sh not found!' && exit 1; fi; else echo 'Initialization already completed. Exiting.'; fi && exit 0"
    networks:
      - invoice-ninja-network
    restart: "no"
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: "10"
    x-casaos:
      volumes:
        - container: /tmp/data
          description:
            en_US: "Container Path: /tmp/data"
            en_us: "Container Path: /tmp/data"
networks:
  invoice-ninja-network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  id: br.com.roqueos.invoice-ninja
  main: invoice-ninja-web
  description:
    en_US: Invoice Ninja is a free and open-source invoice and expense management system. It is a web-based application that allows you to create, manage, and track invoices and expenses.
    en_us: Invoice Ninja is a free and open-source invoice and expense management system. It is a web-based application that allows you to create, manage, and track invoices and expenses.
    pt_br: Invoice Ninja é um sistema aberto de fatura e despesa. Cria orçamento, emite fatura, acompanha pagamento e registra o que entrou e o que saiu.
  tagline:
    en_US: Invoice Ninja
    en_us: Invoice Ninja
    pt_br: Emissão de fatura e controle de despesa, de graça
  developer: invoiceninja
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/invoice-ninja.png
  thumbnail: ""
  tips:
    before_install:
      en_US: |
        Before you install read this: https://community.roqueribeiro.com/t/added-invoice-ninja-to-bigbearcasaos/1697?u=dragonfire1119#p-3214-instructions-3
      en_us: |
        Before you install read this: https://community.roqueribeiro.com/t/added-invoice-ninja-to-bigbearcasaos/1697?u=dragonfire1119#p-3214-instructions-3
  title:
    en_US: Invoice Ninja
    en_us: Invoice Ninja
  category: Finance
  port_map: "8080"
  scheme: http
x-roqueos:
  portaCompartilhada: true
